In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('amazon_products_cleaned.csv')
data.shape

(42433, 9)

In [4]:
data.isnull().sum()

Unnamed: 0             0
Product Category       1
Product Subcategory    1
Product Name           3
Product URL            1
Product Price          1
Product Rating         1
Total Ratings          3
Product Image          1
dtype: int64

In [5]:
data.dropna(inplace=True)
data.shape

(42430, 9)

In [6]:
data.head()

,Unnamed: 0,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,"$1,219.99",4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,$39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,$149.99,4.2,"1,677",https://m.media-amazon.com/images/I/71Sbx9zQN3...

In [7]:
data.tail()

,Unnamed: 0,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
42428,43585,Tools & Home Improvement,Pressure washers,"Westinghouse ePX3100 Electric Pressure Washer,...",https://www.amazon.com/Westinghouse-ePX3100-An...,$139.00,4.6,"6,000",https://m.media-amazon.com/images/I/8133uhKt8Z...
42429,43586,Tools & Home Improvement,Pressure washers,SIMPSON Cleaning CM61083 Clean Machine 3400 PS...,https://www.amazon.com/Simpson-Cleaning-CM6108...,$379.00,4.2,"1,902",https://m.media-amazon.com/images/I/81jMU-KMgf...
42430,43587,Tools & Home Improvement,Pressure washers,"Pressure Washer, 5000PSI 3.2GPM Adjustable Tou...",https://www.amazon.com/Pressure-Adjustable-Ele...,$143.99,4.4,146,https://m.media-amazon.com/images/I/71DJf0+AxI...
42431,43588,Tools & Home Improvement,Pressure washers,Electric Pressure Washer 5000PSI-Max 3.6GPM Po...,https://www.amazon.com/Electric-Pressure-Adjus...,$168.00,4.2,816,https://m.media-amazon.com/images/I/71y05D7V25...
42432,43589,Tools & Home Improvement,Pressure washers,"Pressure Washer, 4800PSI 3.0 GPM Max Electric ...",https://www.amazon.com/Pressure-4800PSI-Electr...,$118.99,4.6,118,https://m.media-amazon.com/images/I/71rsywlYeN...

In [8]:
data.reset_index(inplace=True)

In [9]:
data.head()

,index,Unnamed: 0,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
0,0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,"$1,219.99",4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
2,2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,$39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...
3,3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
4,4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,$149.99,4.2,"1,677",https://m.media-amazon.com/images/I/71Sbx9zQN3...

In [10]:
data['Product ID']=data['Unnamed: 0']
data.drop(columns=['Unnamed: 0'],inplace=True)
data.head()

,index,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image,Product ID
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,"$1,219.99",4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...,0
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...,1
2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,$39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...,2
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...,3
4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,$149.99,4.2,"1,677",https://m.media-amazon.com/images/I/71Sbx9zQN3...,4

In [11]:
data.columns

Index(['index', 'Product Category', 'Product Subcategory', 'Product Name',
       'Product URL', 'Product Price', 'Product Rating', 'Total Ratings',
       'Product Image', 'Product ID'],
      dtype='object')

In [12]:
columns=['Product ID' ,'Product Category', 'Product Subcategory', 'Product Name',
       'Product URL', 'Product Price', 'Product Rating', 'Total Ratings',
       'Product Image']
data=data[columns]
data.head()

,Product ID,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,"$1,219.99",4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,$39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,$149.99,4.2,"1,677",https://m.media-amazon.com/images/I/71Sbx9zQN3...

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42430 entries, 0 to 42429
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product ID           42430 non-null  int64
 1   Product Category     42430 non-null  object
 2   Product Subcategory  42430 non-null  object
 3   Product Name         42430 non-null  object
 4   Product URL          42430 non-null  object
 5   Product Price        42430 non-null  object
 6   Product Rating       42430 non-null  float64
 7   Total Ratings        42430 non-null  object
 8   Product Image        42430 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 2.9+ MB

In [14]:
type(data['Product Price'])

pandas.core.series.Series

In [15]:
data.head()

,Product ID,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,"$1,219.99",4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,$39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,$149.99,4.2,"1,677",https://m.media-amazon.com/images/I/71Sbx9zQN3...

In [16]:
def floatPrice(s: pd.Series) -> pd.Series:
    return (
        s.astype(str)
         .str.replace("$", "", regex=False)
         .str.replace(",", "", regex=False)
         .astype(float)
    )
data['Product Price ($)']=floatPrice(data['Product Price'])

In [17]:
data.columns

Index(['Product ID', 'Product Category', 'Product Subcategory', 'Product Name',
       'Product URL', 'Product Price', 'Product Rating', 'Total Ratings',
       'Product Image', 'Product Price ($)'],
      dtype='object')

In [18]:
columns=['Product ID', 'Product Category', 'Product Subcategory', 'Product Name',
       'Product URL', 'Product Price ($)', 'Product Rating', 'Total Ratings',
       'Product Image']
data=data[columns]
data.head()

,Product ID,Product Category,Product Subcategory,Product Name,Product URL,Product Price ($),Product Rating,Total Ratings,Product Image
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,1219.99,4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,149.99,4.2,"1,677",https://m.media-amazon.com/images/I/71Sbx9zQN3...

In [19]:
data['Product Category'].value_counts()

Product Category
Furniture                   2795
Toys                        2749
Kitchenware                 2443
Beauty & Personal           1723
Groceries                   1480
Home Decor                  1480
Baby Products               1457
Healthcare & Wellness       1448
Footwear                    1440
Office Supplies             1436
Beauty & Personal Care      1432
Pet Supplies                1419
Art & Craft                 1418
Jewelry                     1380
Arts & Crafts               1336
Health & Household          1324
Music Instruments           1318
Art Supplies                1294
Gardening & Outdoor         1293
Travel Accessories          1263
Sports & Outdoors           1261
Automotive                  1234
Tools & Home Improvement    1232
Books                       1227
Camping & Hiking            1156
Music                       1121
Industrial & Scientific     1012
Electronics                  856
Gaming & Accessories         714
Home Appliances              689
Name: count, dtype: int64

# Downloading images

In [20]:
data['Product ID']

0            0
1            1
2            2
3            3
4            4
         ...
42425    43585
42426    43586
42427    43587
42428    43588
42429    43589
Name: Product ID, Length: 42430, dtype: int64

In [21]:
import os
import mimetypes
import pandas as pd
import requests

OUT_DIR  = "images"               # change
ID_COL   = "Product ID"           # change if needed
URL_COL  = "Product Image"        # change if needed

os.makedirs(OUT_DIR, exist_ok=True)


session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0",
    "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
})

def guess_ext(resp, url):
    ct = resp.headers.get("Content-Type", "").split(";")[0].strip()
    ext = mimetypes.guess_extension(ct) if ct else None
    if ext:
        return ext
    # fallback from URL
    tail = url.split("?")[0].lower()
    for e in [".jpg", ".jpeg", ".png", ".webp"]:
        if tail.endswith(e):
            return e
    return ".jpg"

ok, fail = 0, 0
for _, row in data.iterrows():
    pid = str(row[ID_COL])
    url = str(row[URL_COL]) if pd.notna(row[URL_COL]) else ""
    if not url or url == "nan":
        fail += 1
        continue

    try:
        r = session.get(url, stream=True, timeout=(5, 30))
        r.raise_for_status()

        ext = guess_ext(r, url)
        path = os.path.join(OUT_DIR, f"{pid}{ext}")

        with open(path, "wb") as f:
            for chunk in r.iter_content(chunk_size=1024 * 64):
                if chunk:
                    f.write(chunk)

        ok += 1
    except Exception:
        fail += 1

print(f"Downloaded: {ok} | Failed: {fail}")

KeyboardInterrupt:

In [ ]:
data.tail()

In [ ]:
def intTotalRatings(s: pd.Series) -> pd.Series:
    return (
        s.astype(str)
         .str.replace(",", "", regex=False)
         .astype(int)
    )
data['Total Ratings']=intTotalRatings(data['Total Ratings'])
data.head()

In [ ]:
data[data['Product Price ($)']==0]['Product Subcategory'].value_counts()

In [ ]:
# treat 0 as missing
import numpy as np
data.loc[data['Product Price ($)'] <= 0, 'Product Price ($)'] = np.nan

# compute median per subcategory and fill
sub_median = data.groupby('Product Subcategory')['Product Price ($)'].transform("median")
data['Product Price ($)'] = data['Product Price ($)'].fillna(sub_median)

In [ ]:
#data.to_csv('vectors_in_orbit.csv')

In [22]:
data['Product Subcategory'].value_counts()

Product Subcategory
First aid kits        146
Essential oils        146
Face masks            146
Paint brushes         144
Oil paints            143
                     ...
Graphic Cards          14
Washing machines       14
VR headsets            13
Geysers                 7
Mystery & Thriller      5
Name: count, Length: 920, dtype: int64